### docker-android-lite: disable unnecessary emulator features
### Placed in ~/.android/ at container startup
ScreenRecording = off
VirtualScene = off
ModemSimulator = off
VirtioSndCard = off
TvRemote = off
CarRotary = off
CarVHalTable = off
CarVhalReplay = off
MultiDisplay = off
NoDeviceFrame = on
LocationUiV2 = off
GenericSnapshotsUI = off
